### ISSUE TITLE
Nem csiripel

### ISSUE THREAD

**Issue by nerton** [underyx/bkkcsirip#11]
Ha jól látom, twitteren leállt a csirip.

**Comment by underyx** [comment]
Valóban úgy tűnik. Ma este meg tudom nézni. Köszi hogy szoltal!

**Comment by underyx** [comment]
Fixed!

**Comment by nerton** [comment]
Cool. Thx. Vetettem rá egy pillantást, és felmerült bennem a gondolat, hogy jó időket mutat-e. MIntha +2 órás időeltolódás nem adódna hozzá az utc-hez. Csak a 4-es metróból gondolom, amit 1 óra körülre ír, miközben a hírek szerint 3 óra körül volt vele a gond:  http://hvg.hu/itthon/20160803_4_metro_hiba

**Comment by underyx** [comment]
Teljesen lehetséges, megtennéd hogy nyitsz erre egy új issuet? Most
hajnalig utazni fogok és anélkül el fogom ezt felejteni :(
