### ISSUE TITLE
Potenciális időzóna kezelési probléma

### ISSUE THREAD

**Issue by nerton** [underyx/bkkcsirip#12]
Vetettem rá egy pillantást, és felmerült bennem a gondolat, hogy jó időket mutat-e. MIntha +2 órás időeltolódás nem adódna hozzá az utc-hez. Csak a 4-es metróból gondolom, amit 1 óra körülre ír, miközben a  hírek szerint 3 óra körül volt vele a gond:
 http://hvg.hu/itthon/20160803_4_metro_hiba

**Comment by underyx** [comment]
@nerton koszi szepen ezt a bug reportot is! Atraktam egy ideje a scriptet egy masik szerveremre, ami UTC-t hasznal CEST helyett, es nem is jutott eszembe, hogy olyan rosszul irtam meg ezt a programot meg annak idejen, hogy a szerver idozonaja el tudja rontani :(

**Comment by nerton** [comment]
Előfordul az ilyen. Nekem is volt egy oldalam, ami az akutális napi dátum szerint jelenített meg dolgokat, és reggel 8-kor még mindig az előző napot mutatta, mint kiderült azért, mert amerikai szerveren futott, és ottani időzónát használt.  Köszi a javítást.
